version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: reports-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: reports
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: reports-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: reports-server
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/reports
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FRONTEND_URL: http://localhost:5173
      # Add other envs like JWT_SECRET, CLOUDINARY_*, etc. via .env or compose overrides
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: reports-frontend
    restart: unless-stopped
    depends_on:
      - server
    environment:
      # Vite uses this at build time; using compose build-arg would be better
      VITE_BACKEND: http://localhost:5000
    ports:
      - "5173:80"

volumes:
  mongo_data:


